Repository School-of-Company/Bitgoeul-Android, pull requests merged in 2023-10, with the labels that each got.

#7 🔀 ::(#5) - Enable local.properties in the network module
  core/network/build.gradle.kts
Labels: ⚙ Setting

#6 🔀 :: (#4) Android CI Setting
  .github/workflows/android.yml
  app/build.gradle.kts
  build-logic/convention/src/main/java/com/msg/convention/AndroidCoreConventionPlugin.kt
  core/model/build.gradle.kts
  core/model/src/androidTest/java/com/msg/model/ExampleInstrumentedTest.kt
  core/model/src/main/AndroidManifest.xml
  core/model/src/main/java/com/hackathon/model/MyClass.kt
  core/model/src/test/java/com/msg/model/ExampleUnitTest.kt
  settings.gradle.kts
Labels: ⚙ Setting

#11 🔀 :: (#9) gitgnore 재적용
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  gradlew.bat
Labels: 0️⃣ Priority: Critical

#10 CICD알림노예주홍이세팅
  .github/workflows/android.yml
Labels: 0️⃣ Priority: Critical

#13 🔀 :: (#12) - add gradle caching
  .github/workflows/android.yml
Labels: 1️⃣ Priority: High, ⚙ Setting, ⚡️ Simple

#16 🔀 :: (#15) - Set design-system
  app/build.gradle.kts
  app/src/main/java/com/msg/bitgoeul_android/MainActivity.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/theme/Color.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/theme/Theme.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/theme/Type.kt
  core/design-system/src/main/java/com/msg/design_system/theme/Theme.kt
  core/design-system/src/main/java/com/msg/design_system/theme/Type.kt
  core/design-system/src/main/java/com/msg/design_system/theme/color/Color.kt
  core/design-system/src/main/java/com/msg/design_system/theme/color/ColorTheme.kt
  core/design-system/src/main/res/font/pretendard_regular.ttf
  core/design-system/src/main/res/font/pretendard_semibold.ttf
Labels: 1️⃣ Priority: High

#18 🔀 :: (#17) - Create Button, TextField component
  app/src/main/AndroidManifest.xml
  core/design-system/src/main/AndroidManifest.xml
  core/design-system/src/main/java/com/msg/design_system/component/button/BitgoeulButton.kt
  core/design-system/src/main/java/com/msg/design_system/component/button/ButtonState.kt
  core/design-system/src/main/java/com/msg/design_system/component/icon/BitgoeulIcon.kt
  core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
  core/design-system/src/main/java/com/msg/design_system/theme/Theme.kt
  core/design-system/src/main/java/com/msg/design_system/theme/Type.kt
  core/design-system/src/main/java/com/msg/design_system/theme/color/BitgoeulColor.kt
  core/design-system/src/main/java/com/msg/design_system/util/Vibration.kt
  core/design-system/src/main/res/drawable/ic_cancel.xml
  core/design-system/src/main/res/drawable/ic_seeable_disable.xml
  core/design-system/src/main/res/drawable/ic_seeable_enable.xml
Labels: 1️⃣ Priority: High

#20 🔀 :: (#19) - Create FeaturePlugin
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/java/com/msg/convention/AndroidFeatureConventionPlugin.kt
Labels: 1️⃣ Priority: High

#22 🔀 :: (#21) - Set up network on login part
  core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/LoginUseCase.kt
  core/model/src/main/java/com/hackathon/model/MyClass.kt
  core/model/src/main/java/com/msg/model/remote/AuthTokenModel.kt
  core/model/src/main/java/com/msg/model/remote/request/LoginRequest.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
  core/network/src/main/java/com/msg/network/exception/HttpException.kt
  core/network/src/main/java/com/msg/network/exception/NeedLoginException.kt
  core/network/src/main/java/com/msg/network/exception/NetworkException.kt
  core/network/src/main/java/com/msg/network/util/BitgoeulApiHandler.kt
Labels: 1️⃣ Priority: High

#26 🔀 :: (#24) - Save and Refresh Token
  core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  core/datastore/build.gradle.kts
  core/datastore/src/main/java/com/msg/datastore/AuthTokenDataSource.kt
  core/datastore/src/main/java/com/msg/datastore/AuthTokenSerializer.kt
  core/datastore/src/main/java/com/msg/datastore/di/DataSourceModule.kt
  core/datastore/src/main/proto/authToken.proto
  core/domain/src/main/java/com/msg/domain/auth/LoginUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/SaveTokenUseCase.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
Labels: 1️⃣ Priority: High

#27 🔀 :: (#23) - Add Interceptor
  core/network/build.gradle.kts
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
  core/network/src/main/java/com/msg/network/util/AuthInterceptor.kt
  core/network/src/main/java/com/msg/network/util/DateTimeFormatter.kt
Labels: 1️⃣ Priority: High

#28 🔀 :: (#25) - Change Greayscale
  core/design-system/src/main/java/com/msg/design_system/theme/color/BitgoeulColor.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#30 🔀 :: (#29) - Set up network on student sign up
  core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpStudentUseCase.kt
  core/model/src/main/java/com/msg/model/remote/HighSchool.kt
  core/model/src/main/java/com/msg/model/remote/request/SignUpStudentRequest.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#37 🔀 :: (#33) - Apply changed Textfield
  core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#38 🔀 :: (#34) - Set up network on professor sign up part
  core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpJobClubTeacherUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpProfessorUseCase.kt
  core/model/src/main/java/com/msg/model/remote/request/SignUpProfessorRequest.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#39 🔀 :: (#35) - Set up network on government sign up part
  core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpGovernment.kt
  core/model/src/main/java/com/msg/model/remote/request/SignUpGovernmentRequest.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#40 🔀 :: (#36) - Set up network on company instructor sign up part
  core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpCompanyInstructorUseCase.kt
  core/model/src/main/java/com/msg/model/remote/request/SignUpCompanyInstructorRequest.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#43 🔀 :: (#41) - Set up network on Logout part
  core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/LogoutUseCase.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#44 🔀 :: (#42) - Set up network on withdraw part
  core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/WithdrawUseCase.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#47 🔀 :: (#46) - Change to see last digit in password textfield
  core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
  core/design-system/src/main/java/com/msg/design_system/util/LastPasswordVisibleVisualTransformation.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple
