Repository School-of-Company/Bitgoeul-Android, pull requests merged in 2023-11, with the labels that each got.

#52 🔀 :: (#48) theme.xml NoActionBar로 설정
  app/src/main/res/values/themes.xml
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
Labels: 1️⃣ Priority: High

#55 🔀 :: (#54) Lecture API Setting
  core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepository.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/LoginUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/LogoutUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/SaveTokenUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpCompanyInstructorUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpGovernment.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpJobClubTeacherUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpProfessorUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpStudentUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/WithdrawUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/ApprovePendingLectureUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/GetDetailLectureUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/GetLectureListUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/LectureApplicationUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/OpenLectureUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/RejectPendingLecture.kt
  core/model/src/main/java/com/msg/model/remote/enumdatatype/HighSchool.kt
  core/model/src/main/java/com/msg/model/remote/enumdatatype/LectureStatus.kt
  core/model/src/main/java/com/msg/model/remote/enumdatatype/LectureType.kt
  core/model/src/main/java/com/msg/model/remote/model/auth/AuthTokenModel.kt
  core/model/src/main/java/com/msg/model/remote/model/lecture/DetailLectureModel.kt
  core/model/src/main/java/com/msg/model/remote/model/lecture/LectureListModel.kt
  core/model/src/main/java/com/msg/model/remote/request/auth/LoginRequest.kt
  core/model/src/main/java/com/msg/model/remote/request/auth/SignUpCompanyInstructorRequest.kt
  core/model/src/main/java/com/msg/model/remote/request/auth/SignUpGovernmentRequest.kt
  core/model/src/main/java/com/msg/model/remote/request/auth/SignUpJobClubTeacherRequest.kt
  core/model/src/main/java/com/msg/model/remote/request/auth/SignUpProfessorRequest.kt
  core/model/src/main/java/com/msg/model/remote/request/auth/SignUpStudentRequest.kt
  core/model/src/main/java/com/msg/model/remote/request/lecture/OpenLectureRequest.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/api/LectureAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
Labels: 1️⃣ Priority: High

#57 🔀 :: (#49) - Publishing Sign Up Page
  core/design-system/src/main/java/com/msg/design_system/component/bottomsheet/BitgoeulBottomSheet.kt
  core/design-system/src/main/java/com/msg/design_system/component/bottomsheet/SelectedIndicator.kt
  core/design-system/src/main/java/com/msg/design_system/component/bottomsheet/Selector.kt
  core/design-system/src/main/java/com/msg/design_system/component/icon/BitgoeulIcon.kt
  core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
  core/design-system/src/main/java/com/msg/design_system/component/topbar/GoBackTopBar.kt
  core/design-system/src/main/java/com/msg/design_system/util/hideKeyboard.kt
  core/design-system/src/main/res/drawable/ic_back.xml
  core/domain/src/main/java/com/msg/domain/auth/SignUpGovernment.kt
  core/model/src/main/java/com/msg/model/remote/enumdatatype/HighSchool.kt
  core/model/src/main/java/com/msg/model/ui/BitgoeulList.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/sign-up/.gitignore
  feature/sign-up/build.gradle.kts
  feature/sign-up/src/androidTest/java/com/msg/sign_up/ExampleInstrumentedTest.kt
  feature/sign-up/src/main/AndroidManifest.xml
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/component/SignUpBottomSheet.kt
  feature/sign-up/src/main/java/com/msg/sign_up/data/SignUpLists.kt
  feature/sign-up/src/main/java/com/msg/sign_up/util/searchClubBySchool.kt
  feature/sign-up/src/main/java/com/msg/sign_up/util/searchingInList.kt
  feature/sign-up/src/test/java/com/msg/sign_up/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 1️⃣ Priority: High

#60 🔀 :: (#51) Connect Auth Login API
  app/src/main/java/com/msg/bitgoeul_android/MainActivity.kt
  core/domain/src/main/java/com/msg/domain/exception/HttpException.kt
  core/domain/src/main/java/com/msg/domain/exception/NeedLoginException.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/viewmodel/AuthViewModel.kt
  feature/login/src/main/java/com/bitgoeul/login/viewmodel/util/Event.kt
  feature/login/src/main/java/com/bitgoeul/login/viewmodel/util/errorHandling.kt
Labels: 1️⃣ Priority: High

#62 🔀 :: (#45) - Set up SAA
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/msg/bitgoeul_android/BitgoeulApplication.kt
  app/src/main/java/com/msg/bitgoeul_android/MainActivity.kt
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  app/src/main/java/com/msg/bitgoeul_android/navigation/TopLevelDestination.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulApp.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulAppState.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/navigation/LoginNavigation.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/navigation/SignUpNavigation.kt
Labels: 1️⃣ Priority: High

#63 🔀 :: (#53) - Set up network on bbozzak teacher sign up part
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpBbozzakTeacherUseCase.kt
  core/domain/src/main/java/com/msg/domain/auth/SignUpGovernmentUseCase.kt
  core/model/src/main/java/com/msg/model/remote/request/auth/SignUpBbozzakTeacherRequest.kt
  core/network/src/main/java/com/msg/network/api/AuthAPI.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#66 🔀 :: (#64) - Set up network on add student activity info
  core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/AddStudentActivityInfoUseCase.kt
  core/model/src/main/java/com/msg/model/remote/model/activity/StudentActivityModel.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
Labels: 1️⃣ Priority: High

#68 🔀 :: (#67) - Set up network on edit student activity info
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/EditStudentActivityInfoUseCase.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#71 🔀 :: (#69) - Set up network on approve student activity info
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/ApproveStudentActivityInfoUseCase.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#73 🔀 :: (#72) - Set up network on reject student activity info
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/RejectStudentActivityInfoUseCase.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#75 🔀 :: (#74) - Set up network on delete student activity info
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/DeleteStudentActivityInfoUseCase.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#77 🔀 :: (#76) - Set up network on inquiry my student activity info list
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/InquiryMyStudentActivityInfoListUseCase.kt
  core/model/src/main/java/com/msg/model/remote/enumdatatype/ApproveStatus.kt
  core/model/src/main/java/com/msg/model/remote/model/activity/InquiryStudentActivityModel.kt
  core/model/src/main/java/com/msg/model/remote/response/activity/InquiryStudentActivityListResponse.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#79 🔀 :: (#78) - Set up network on inquiry activity list
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/InquiryStudentActivityInfoListUseCase.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#81 🔀 :: (#80) - Set up network on inquiry entire student activity info list
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/InquiryEntireStudentActivityInfoListUseCase.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#83 🔀 :: (#82) - Set up inquiry detail student activity info
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/InquiryDetailStudentActivityInfoUseCase.kt
  core/model/src/main/java/com/msg/model/remote/response/activity/InquiryDetailStudentActivityInfoResponse.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#86 🔀 :: (#85) - Set up network on change password
  core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/user/UserRepository.kt
  core/data/src/main/java/com/msg/data/repository/user/UserRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/ChangePasswordUseCase.kt
  core/model/src/main/java/com/msg/model/remote/request/user/ChangePasswordRequest.kt
  core/network/src/main/java/com/msg/network/api/UserAPI.kt
  core/network/src/main/java/com/msg/network/datasource/user/UserDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/user/UserDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
Labels: 1️⃣ Priority: High

#87 🔀 :: (#65) - Lock screen rotate
  core/design-system/src/main/java/com/msg/design_system/util/LockScreenOrientation.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
Labels: 3️⃣ Priority: Low

#90 🔀 :: (#89) - Refactoring loginscreen for easier ui test
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/viewmodel/AuthViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#92 🔀 :: (#88) - Fix title text in LoginScreen
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#93 🔀 :: (#91) - Active login button
  app/src/main/AndroidManifest.xml
  core/design-system/src/main/java/com/msg/design_system/component/button/BitgoeulButton.kt
  core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
  core/design-system/src/main/java/com/msg/design_system/util/checkRegex.kt
  core/network/src/main/java/com/msg/network/util/DateTimeFormatter.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
Labels: 1️⃣ Priority: High

#96 🔀 :: (#70) - Set up network frequently asked questions
  core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepository.kt
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/faq/AddFrequentlyAskedQuestionUseCase.kt
  core/model/src/main/java/com/msg/model/remote/request/faq/AddFrequentlyAskedQuestionsRequest.kt
  core/network/src/main/java/com/msg/network/api/FaqAPI.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
Labels: 1️⃣ Priority: High

#99 Feature/#97 set up network get faq list
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepository.kt
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/faq/GetFrequentlyAskedQuestionsListUseCase.kt
  core/model/src/main/java/com/msg/model/remote/response/faq/FrequentlyAskedQuestionsListResponse.kt
  core/network/src/main/java/com/msg/network/api/FaqAPI.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#101 🔀 :: (#100) Set Up Get FAQ Detail Network
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepository.kt
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/faq/GetFrequentlyAskedQuestionsDetailUseCase.kt
  core/model/src/main/java/com/msg/model/remote/response/faq/GetFrequentlyAskedQuestionDetailResponse.kt
  core/network/src/main/java/com/msg/network/api/FaqAPI.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#103 🔀 :: (#102) Apply Lecture API Model to Response
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepository.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepositoryImpl.kt
  core/model/src/main/java/com/msg/model/remote/response/lecture/DetailLectureResponse.kt
  core/model/src/main/java/com/msg/model/remote/response/lecture/LectureListResponse.kt
  core/network/src/main/java/com/msg/network/api/LectureAPI.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSourceImpl.kt
Labels: 1️⃣ Priority: High

#107 🔀 :: (#105) Set Up Get Certification List Role Teacher
  core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
  core/data/src/main/java/com/msg/data/repository/certification/CertificationRepository.kt
  core/data/src/main/java/com/msg/data/repository/certification/CertificationRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/certification/GetDetailCertificationListUseCase.kt
  core/model/src/main/java/com/msg/model/remote/response/certification/DetailCertificationResponse.kt
  core/network/src/main/java/com/msg/network/api/CertificationAPI.kt
  core/network/src/main/java/com/msg/network/api/FaqAPI.kt
  core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
Labels: 1️⃣ Priority: High

#104 🔀 :: (#58) LoginScreen Box -> Surface로 변경
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
Labels: 3️⃣ Priority: Low

#108 🔀 :: (#84) - publishing student activity
  app/src/main/AndroidManifest.xml
  core/design-system/src/main/java/com/msg/design_system/component/bottomsheet/BitgoeulBottomSheet.kt
  core/design-system/src/main/java/com/msg/design_system/component/button/BitgoeulButton.kt
  core/design-system/src/main/java/com/msg/design_system/component/dialog/NegativeActionDialog.kt
  core/design-system/src/main/java/com/msg/design_system/component/dialog/PositiveActionDialog.kt
  core/design-system/src/main/java/com/msg/design_system/component/icon/BitgoeulIcon.kt
  core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
  core/design-system/src/main/res/drawable/ic_picker_arrow_selected.xml
  core/design-system/src/main/res/values/strings.xml
  core/model/src/main/java/com/msg/model/remote/enumdatatype/Authority.kt
  core/model/src/main/java/com/msg/model/remote/model/activity/InquiryStudentActivityModel.kt
  core/model/src/main/java/com/msg/model/remote/response/activity/InquiryDetailStudentActivityInfoResponse.kt
  core/ui/src/main/java/com/msg/ui/StudentActivityCard.kt
  core/ui/src/main/java/com/msg/ui/StudentActivityList.kt
  core/ui/src/main/java/com/msg/ui/util/dateFormatter.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailSettingScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureOpenScreen.kt
  feature/student-activity/.gitignore
  feature/student-activity/build.gradle.kts
  feature/student-activity/src/androidTest/java/com/msg/student_activity/ExampleInstrumentedTest.kt
  feature/student-activity/src/main/AndroidManifest.xml
  feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailSettingScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/AddActivityScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/StudentActivityScreen.kt
  feature/student-activity/src/test/java/com/msg/student_activity/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High

#109 🔀 :: (#106) Change LectureUseCase kotlin.runCatching
  core/domain/src/main/java/com/msg/domain/lecture/ApprovePendingLectureUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/GetDetailLectureUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/GetLectureListUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/LectureApplicationUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/OpenLectureUseCase.kt
  core/domain/src/main/java/com/msg/domain/lecture/RejectPendingLectureUseCase.kt
Labels: 3️⃣ Priority: Low

#113 🔀 :: (#112) - Save authority in local when login
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepositoryImpl.kt
  core/datastore/src/main/java/com/msg/datastore/AuthTokenDataSource.kt
  core/datastore/src/main/proto/authToken.proto
  core/model/src/main/java/com/msg/model/remote/model/auth/AuthTokenModel.kt
Labels: 1️⃣ Priority: High
