Repository School-of-Company/Bitgoeul-Android, pull requests merged in 2024-05, with the labels that each got.

#173 🔀 :: (#162) - Add faq and some change in MainPage
  app/build.gradle.kts
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepository.kt
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepositoryImpl.kt
  core/design-system/src/main/java/com/msg/design_system/component/dialog/BitgoeulAlertDialog.kt
  core/domain/src/main/java/com/msg/domain/faq/GetFrequentlyAskedQuestionsDetailUseCase.kt
  core/model/src/main/java/com/msg/model/remote/response/faq/FrequentlyAskedQuestionsListResponse.kt
  core/network/src/main/java/com/msg/network/api/FaqAPI.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSourceImpl.kt
  feature/main/src/main/java/com/msg/main/FaqViewModel.kt
  feature/main/src/main/java/com/msg/main/MainPageScreen.kt
  feature/main/src/main/java/com/msg/main/banner/industry/AiFusionAndIntegrationBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/CultureIndustryBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/EnergyIndustryBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/FutureTransportationBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/MedicalHealthBanner.kt
  feature/main/src/main/java/com/msg/main/component/AddFaqItem.kt
  feature/main/src/main/java/com/msg/main/component/ClubChipView.kt
  feature/main/src/main/java/com/msg/main/component/FaqItem.kt
  feature/main/src/main/java/com/msg/main/component/FaqSection.kt
  feature/main/src/main/java/com/msg/main/component/SchoolClubGridView.kt
  feature/main/src/main/java/com/msg/main/navigation/MainPageNavigation.kt
  feature/main/src/main/java/com/msg/main/util/Event.kt
  feature/main/src/main/java/com/msg/main/util/errorHandling.kt
  feature/post/src/main/java/com/msg/post/PostScreen.kt
Labels: 1️⃣ Priority: High

#174 🔀 :: (#172) Lecture 세부설정 변경사항 퍼블리싱
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepository.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepositoryImpl.kt
  core/design-system/src/main/java/com/msg/design_system/component/bottomsheet/BitgoeulBottomSheet.kt
  core/design-system/src/main/java/com/msg/design_system/component/text/BitgoeulSubjectText.kt
  core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
  core/design-system/src/main/res/values/strings.xml
  core/domain/src/main/java/com/msg/domain/lecture/SearchLineUseCase.kt
  core/model/src/main/java/com/msg/model/remote/request/lecture/OpenLectureRequest.kt
  core/network/src/main/java/com/msg/network/api/LectureAPI.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSourceImpl.kt
  feature/email/src/main/java/com/bitgoeul/email/InputNewPasswordScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailSettingScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/component/AddLectureDatesButton.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureCategoryTag.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingBottomSheet.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingInfoCard.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingList.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingSearchDialog.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingTextField.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureSettingTag.kt
  feature/lecture/src/main/java/com/msg/lecture/util/dateFormatter.kt
  feature/lecture/src/main/java/com/msg/lecture/util/timeFormatter.kt
  feature/lecture/src/main/java/com/msg/lecture/viewmodel/LectureViewModel.kt
Labels: 0️⃣ Priority: Critical

#180 Feature/#178 add completion of lecture
  app/build.gradle.kts
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  core/data/src/main/java/com/msg/data/repository/certification/CertificationRepository.kt
  core/data/src/main/java/com/msg/data/repository/certification/CertificationRepositoryImpl.kt
  core/design-system/src/main/java/com/msg/design_system/component/icon/BitgoeulIcon.kt
  core/design-system/src/main/java/com/msg/design_system/component/topbar/DetailSettingTopBar.kt
  core/design-system/src/main/res/drawable/ic_human.xml
  core/domain/src/main/java/com/msg/domain/certification/EditCertificationUseCase.kt
  core/model/src/main/java/com/msg/model/remote/request/certification/WriteCertificationRequest.kt
  core/model/src/main/java/com/msg/model/remote/response/club/StudentBelongClubResponse.kt
  core/network/src/main/java/com/msg/network/api/CertificationAPI.kt
  core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSourceImpl.kt
  feature/certification/.gitignore
  feature/certification/build.gradle.kts
  feature/certification/src/androidTest/java/com/msg/certification/ExampleInstrumentedTest.kt
  feature/certification/src/main/AndroidManifest.xml
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/CertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/CertificationViewModel.kt
  feature/certification/src/main/java/com/msg/certification/component/AddAcquisitionDateSection.kt
  feature/certification/src/main/java/com/msg/certification/component/AddCertificationSection.kt
  feature/certification/src/main/java/com/msg/certification/component/CertificationItem.kt
  feature/certification/src/main/java/com/msg/certification/component/CertificationSection.kt
  feature/certification/src/main/java/com/msg/certification/component/FinishedLectureItem.kt
  feature/certification/src/main/java/com/msg/certification/component/FinishedLectureSection.kt
  feature/certification/src/main/java/com/msg/certification/component/StudentInfoSection.kt
  feature/certification/src/main/java/com/msg/certification/navigation/CertificationNavigation.kt
  feature/certification/src/main/java/com/msg/certification/util/Event.kt
  feature/certification/src/main/java/com/msg/certification/util/errorHandling.kt
  feature/certification/src/test/java/com/msg/certification/ExampleUnitTest.kt
  feature/club/src/main/java/com/msg/club/ClubViewModel.kt
  feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailSettingScreen.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High

#182 🔀 :: (#181) - Add redirection to main page when login succeed
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/navigation/LoginNavigation.kt
Labels: 1️⃣ Priority: High

#185 🔀 :: (#184) - Add BottomNavigation
  app/src/main/java/com/msg/bitgoeul_android/navigation/TopLevelDestination.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulApp.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulAppState.kt
  core/design-system/src/main/java/com/msg/design_system/component/navigation/BitgoeulNavigationBar.kt
Labels: 1️⃣ Priority: High

#187 Refactoring sign up
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  core/design-system/src/main/java/com/msg/design_system/component/icon/BitgoeulIcon.kt
  core/design-system/src/main/res/drawable/ic_big_check.xml
  core/model/src/main/java/com/msg/model/remote/request/auth/SignUpGovernmentRequest.kt
  core/model/src/main/java/com/msg/model/ui/BitgoeulList.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpFinishScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpViewModel.kt
  feature/sign-up/src/main/java/com/msg/sign_up/navigation/SignUpNavigation.kt
  feature/sign-up/src/main/java/com/msg/sign_up/util/Event.kt
  feature/sign-up/src/main/java/com/msg/sign_up/util/errorHandling.kt
  feature/sign-up/src/main/java/com/msg/sign_up/util/searchClubBySchool.kt
Labels: 1️⃣ Priority: High

#189 🔀 :: (#59) android.yml branch 네이밍 변경
  .github/workflows/android.yml
Labels: 1️⃣ Priority: High

#191 🔀 :: (#137) Activity API 변경사항, 컨벤션 적용
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/activity/GetDetailStudentActivityInfoUseCase.kt
  core/domain/src/main/java/com/msg/domain/activity/GetEntireStudentActivityInfoListUseCase.kt
  core/domain/src/main/java/com/msg/domain/activity/GetMyStudentActivityInfoListUseCase.kt
  core/domain/src/main/java/com/msg/domain/activity/GetStudentActivityInfoListUseCase.kt
  core/model/src/main/java/com/msg/model/remote/model/activity/GetStudentActivityModel.kt
  core/model/src/main/java/com/msg/model/remote/response/activity/GetDetailStudentActivityInfoResponse.kt
  core/model/src/main/java/com/msg/model/remote/response/activity/GetStudentActivityListResponse.kt
  core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
  core/ui/src/main/java/com/msg/ui/StudentActivityCard.kt
  core/ui/src/main/java/com/msg/ui/StudentActivityList.kt
  feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/StudentActivityScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/viewmodel/StudentActivityViewModel.kt
Labels: 2️⃣ Priority: Medium

#193 🔀 :: (#190) - Add application sign up button
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
Labels: 1️⃣ Priority: High

#195 🔀 :: (#192) 콜백 함수 네이밍 컨벤션 적용
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulApp.kt
  core/design-system/src/main/java/com/msg/design_system/component/bottomsheet/BitgoeulBottomSheet.kt
  core/design-system/src/main/java/com/msg/design_system/component/bottomsheet/SelectedIndicator.kt
  core/design-system/src/main/java/com/msg/design_system/component/bottomsheet/Selector.kt
  core/design-system/src/main/java/com/msg/design_system/component/button/BitgoeulButton.kt
  core/design-system/src/main/java/com/msg/design_system/component/checkbox/BitgoeulCheckBox.kt
  core/design-system/src/main/java/com/msg/design_system/component/dialog/LectureApplicationDialog.kt
  core/design-system/src/main/java/com/msg/design_system/component/navigation/BitgoeulNavigationBar.kt
  core/design-system/src/main/java/com/msg/design_system/component/picker/BitgoeulPicker.kt
  core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
  core/design-system/src/main/java/com/msg/design_system/component/topbar/GoBackTopBar.kt
  core/network/build.gradle.kts
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/component/AddCertificationSection.kt
  feature/club/src/main/java/com/msg/club/ClubDetailScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/EmailSendInformScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputEmailScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputNewPasswordScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/PasswordChangeSuccessScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/navigation/EmailNavigation.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailSettingScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureListScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureTakingStudentListScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/component/AddLectureDatesButton.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureCard.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingInfoCard.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingList.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingTextField.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetatilSettingDepartmentCard.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDomainBottomSheet.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureFilterDialog.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureList.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureSettingTag.kt
  feature/lecture/src/main/java/com/msg/lecture/navigation/LectureNavigation.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/navigation/LoginNavigation.kt
  feature/my-page/src/main/java/com/example/my_page/PasswordChangeScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailSettingScreen.kt
  feature/post/src/main/java/com/msg/post/component/AddLinkSection.kt
  feature/post/src/main/java/com/msg/post/navigation/PostNavigation.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpFinishScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/component/SignUpBottomSheet.kt
  feature/sign-up/src/main/java/com/msg/sign_up/navigation/SignUpNavigation.kt
  feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailSettingScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/navigation/StudentActivityNavigation.kt
Labels: 3️⃣ Priority: Low

#198 🔀 :: (#194) 함수 접근 제어자 변경
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/CertificationScreen.kt
  feature/club/src/main/java/com/msg/club/ClubDetailScreen.kt
  feature/club/src/main/java/com/msg/club/ClubScreen.kt
  feature/club/src/main/java/com/msg/club/component/ClubInfoSection.kt
  feature/club/src/main/java/com/msg/club/component/ClubMemberInfoItem.kt
  feature/club/src/main/java/com/msg/club/component/ClubMemberInfoListSection.kt
  feature/club/src/main/java/com/msg/club/component/ClubResultItem.kt
  feature/club/src/main/java/com/msg/club/component/ClubResultList.kt
  feature/email/src/main/java/com/bitgoeul/email/EmailSendInformScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputEmailScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputNewPasswordScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/PasswordChangeSuccessScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailSettingScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureListScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureOpenScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureTakingStudentListScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/component/AddLectureDatesButton.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureCard.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureCategoryTag.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingInfoCard.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingList.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetailSettingTextField.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDetatilSettingDepartmentCard.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDomainBottomSheet.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureFilterDialog.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureList.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureSettingTag.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/main/src/main/java/com/msg/main/MainPageScreen.kt
  feature/main/src/main/java/com/msg/main/banner/club/AiFusionAndIntegrationClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/club/CultureIndustryClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/club/EnergyIndustryClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/club/FutureTransportClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/club/MedicalHealthClubBanner.kt
  feature/main/src/main/java/com/msg/main/component/AddFaqItem.kt
  feature/main/src/main/java/com/msg/main/component/BitgoeulInfoCardView.kt
  feature/main/src/main/java/com/msg/main/component/ClubChipView.kt
  feature/main/src/main/java/com/msg/main/component/ClubInfoCardView.kt
  feature/main/src/main/java/com/msg/main/component/CollegeCardView.kt
  feature/main/src/main/java/com/msg/main/component/FaqItem.kt
  feature/main/src/main/java/com/msg/main/component/FaqSection.kt
  feature/main/src/main/java/com/msg/main/component/GovernmentBannerItem.kt
  feature/main/src/main/java/com/msg/main/component/HighSchoolCardView.kt
  feature/main/src/main/java/com/msg/main/component/HorizontalInfiniteLoopPager.kt
  feature/main/src/main/java/com/msg/main/component/SchoolClubGridView.kt
  feature/my-page/src/main/java/com/example/my_page/MyPageScreen.kt
  feature/my-page/src/main/java/com/example/my_page/PasswordChangeScreen.kt
  feature/my-page/src/main/java/com/example/my_page/component/AccountInfoView.kt
  feature/my-page/src/main/java/com/example/my_page/component/AccountSettingView.kt
  feature/my-page/src/main/java/com/example/my_page/component/MyInfoView.kt
  feature/post/src/main/java/com/msg/post/PostAddScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailSettingScreen.kt
  feature/post/src/main/java/com/msg/post/PostScreen.kt
  feature/post/src/main/java/com/msg/post/component/AddLinkSection.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpFinishScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/component/SignUpBottomSheet.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor
