Repository School-of-Company/Bitgoeul-Android, pull requests merged in 2024-06, with the labels that each got.

#200 🔀 :: (#196) 로그인 데이터 처리 과정 수정
  core/design-system/src/main/ic_launcher-playstore.png
  core/design-system/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  core/design-system/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  core/design-system/src/main/res/values/ic_launcher_background.xml
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#201 🔀 :: (#199) Unused Import문을 삭제했습니다
  app/src/main/java/com/msg/bitgoeul_android/navigation/TopLevelDestination.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulApp.kt
  core/datastore/src/main/java/com/msg/datastore/AuthTokenDataSource.kt
  core/design-system/src/main/java/com/msg/design_system/component/checkbox/BitgoeulCheckBox.kt
  core/design-system/src/main/java/com/msg/design_system/component/icon/BitgoeulIcon.kt
  core/design-system/src/main/java/com/msg/design_system/component/topbar/DetailSettingTopBar.kt
  core/model/src/main/java/com/msg/model/remote/response/lecture/GetTakingLectureStudentListResponse.kt
  core/ui/src/main/java/com/msg/ui/StudentActivityCard.kt
  core/ui/src/main/java/com/msg/ui/StudentActivityList.kt
  feature/certification/src/androidTest/java/com/msg/certification/ExampleInstrumentedTest.kt
  feature/certification/src/main/AndroidManifest.xml
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/CertificationViewModel.kt
  feature/certification/src/main/java/com/msg/certification/component/CertificationItem.kt
  feature/certification/src/main/java/com/msg/certification/navigation/CertificationNavigation.kt
  feature/certification/src/test/java/com/msg/certification/ExampleUnitTest.kt
  feature/club/src/main/java/com/msg/club/ClubDetailScreen.kt
  feature/club/src/main/java/com/msg/club/ClubScreen.kt
  feature/club/src/main/java/com/msg/club/ClubViewModel.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureListScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureOpenScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureDomainBottomSheet.kt
  feature/lecture/src/main/java/com/msg/lecture/util/timeFormatter.kt
  feature/lecture/src/main/java/com/msg/lecture/viewmodel/LectureViewModel.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/viewmodel/AuthViewModel.kt
  feature/main/src/main/java/com/msg/main/FaqViewModel.kt
  feature/main/src/main/java/com/msg/main/MainPageScreen.kt
  feature/my-page/src/main/java/com/example/my_page/MyPageScreen.kt
  feature/my-page/src/main/java/com/example/my_page/MyPageViewModel.kt
  feature/my-page/src/main/java/com/example/my_page/component/MyInfoView.kt
  feature/post/src/main/java/com/msg/post/PostDetailScreen.kt
  feature/post/src/main/java/com/msg/post/PostScreen.kt
  feature/post/src/main/java/com/msg/post/PostViewModel.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpViewModel.kt
  feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailScreen.kt
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#203 🔀 :: (#202) 비동기 함수 처리 키워드 및 로직 수정
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
  core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/admin/AdminRepository.kt
  core/data/src/main/java/com/msg/data/repository/admin/AdminRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/certification/CertificationRepository.kt
  core/data/src/main/java/com/msg/data/repository/certification/CertificationRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/club/ClubRepository.kt
  core/data/src/main/java/com/msg/data/repository/club/ClubRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/email/EmailRepository.kt
  core/data/src/main/java/com/msg/data/repository/email/EmailRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepository.kt
  core/data/src/main/java/com/msg/data/repository/faq/FaqRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepository.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/post/PostRepository.kt
  core/data/src/main/java/com/msg/data/repository/post/PostRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/user/UserRepository.kt
  core/data/src/main/java/com/msg/data/repository/user/UserRepositoryImpl.kt
  core/datastore/src/main/java/com/msg/datastore/AuthTokenDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/admin/AdminDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/admin/AdminDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/club/ClubDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/club/ClubDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/email/EmailDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/email/EmailDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/post/PostDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/post/PostDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/user/UserDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/user/UserDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/util/AuthInterceptor.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#206 🔀 :: (#204) AuthTokenDataSource의 함수 수정
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepositoryImpl.kt
  core/datastore/src/main/java/com/msg/datastore/AuthTokenDataSource.kt
  core/network/src/main/java/com/msg/network/util/AuthInterceptor.kt
  core/network/src/main/java/com/msg/network/util/DateTimeFormatter.kt
  feature/login/src/main/java/com/bitgoeul/login/viewmodel/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️performance, 🐞 Bug

#209 🔀 :: (#208) Toast 생성 함수 만들기
  core/ui/src/main/java/com/msg/ui/makeToast.kt
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/EmailSendInformScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputNewPasswordScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#210 🔀 :: (#207) AuthTokenDataSource 분리
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/msg/data/repository/auth/AuthRepositoryImpl.kt
  core/datastore/src/main/java/com/msg/datastore/datasource/AuthTokenDataSource.kt
  core/datastore/src/main/java/com/msg/datastore/datasource/AuthTokenDataSourceImpl.kt
  core/datastore/src/main/java/com/msg/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/msg/datastore/di/LocalDataSourceModule.kt
  core/network/src/main/java/com/msg/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/msg/network/util/AuthInterceptor.kt
  feature/certification/src/main/java/com/msg/certification/CertificationViewModel.kt
  feature/club/src/main/java/com/msg/club/ClubViewModel.kt
  feature/lecture/src/main/java/com/msg/lecture/viewmodel/LectureViewModel.kt
  feature/main/src/main/java/com/msg/main/FaqViewModel.kt
  feature/post/src/main/java/com/msg/post/PostViewModel.kt
  feature/student-activity/src/main/java/com/msg/student_activity/viewmodel/StudentActivityViewModel.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#213 🔀 :: (#211) ViewModel 함수 접근제어자 변경
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/CertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/viewmodel/CertificationViewModel.kt
  feature/club/src/main/java/com/msg/club/ClubDetailScreen.kt
  feature/club/src/main/java/com/msg/club/ClubScreen.kt
  feature/club/src/main/java/com/msg/club/viewmodel/ClubViewModel.kt
  feature/email/src/main/java/com/bitgoeul/email/viewmodel/EmailViewModel.kt
  feature/lecture/src/main/java/com/msg/lecture/viewmodel/LectureViewModel.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/util/Event.kt
  feature/login/src/main/java/com/bitgoeul/login/util/errorHandling.kt
  feature/login/src/main/java/com/bitgoeul/login/viewmodel/AuthViewModel.kt
  feature/main/src/main/java/com/msg/main/MainPageScreen.kt
  feature/main/src/main/java/com/msg/main/viewmodel/FaqViewModel.kt
  feature/my-page/src/main/java/com/example/my_page/MyPageScreen.kt
  feature/my-page/src/main/java/com/example/my_page/PasswordChangeScreen.kt
  feature/my-page/src/main/java/com/example/my_page/viewmodel/MyPageViewModel.kt
  feature/post/src/main/java/com/msg/post/PostAddScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailSettingScreen.kt
  feature/post/src/main/java/com/msg/post/PostScreen.kt
  feature/post/src/main/java/com/msg/post/viewmodel/PostViewModel.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/viewmodel/SignUpViewModel.kt
  feature/student-activity/src/main/java/com/msg/student_activity/StudentActivityScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/viewmodel/StudentActivityViewModel.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor, ⚡️ Simple

#216 🔀 :: (#215) - Delete suspicious cpp package and files
  feature/email/src/main/cpp/CMakeLists.txt
  feature/email/src/main/cpp/email.cpp
  feature/lecture/src/main/cpp/CMakeLists.txt
  feature/lecture/src/main/cpp/lecture.cpp
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#223 🔀 :: (#220) DataSource내의 API 통신 요청 중복 로직 개선
  core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/admin/AdminDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/club/ClubDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/email/EmailDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/post/PostDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/user/UserDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/util/BitgoeulApiHandler.kt
  core/network/src/main/java/com/msg/network/util/makeRequest.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️performance

#225 뒤로가기 연속 클릭시 네비게이션 오류
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, ⚡️performance

#226 🔀 :: (#222) - GET 요청 API를 사용하는 함수 접두사 변경
  core/data/src/main/java/com/msg/data/mapper/user/InquiryMyPageMapper.kt
  core/data/src/main/java/com/msg/data/repository/user/UserRepository.kt
  core/data/src/main/java/com/msg/data/repository/user/UserRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/usecase/user/GetMyPageUseCase.kt
  core/model/src/main/java/com/msg/model/entity/user/GetMyPageEntity.kt
  core/model/src/main/java/com/msg/model/model/lecture/LectureDates.kt
  core/network/src/main/java/com/msg/network/api/UserAPI.kt
  core/network/src/main/java/com/msg/network/datasource/user/UserDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/user/UserDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/response/user/GetMyPageResponse.kt
  feature/my-page/src/main/java/com/example/my_page/MyPageScreen.kt
  feature/my-page/src/main/java/com/example/my_page/component/AccountInfoView.kt
  feature/my-page/src/main/java/com/example/my_page/component/MyInfoView.kt
  feature/my-page/src/main/java/com/example/my_page/viewmodel/MyPageViewModel.kt
Labels: ⚡️ Simple

#227 🔀 :: (#221) popUpTo Navigate 적용
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulAppState.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️ Simple, ⚡️performance

#230 🔀 :: (#228) - Moshi 라이브러리 직렬화를 사용하여 Gson의 단점을 보완하였습니다
  core/network/build.gradle.kts
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
  core/network/src/main/java/com/msg/network/request/admin/GetUserListRequest.kt
  core/network/src/main/java/com/msg/network/request/auth/FindPasswordRequest.kt
  core/network/src/main/java/com/msg/network/request/auth/LoginRequest.kt
  core/network/src/main/java/com/msg/network/request/auth/SignUpBbozzakTeacherRequest.kt
  core/network/src/main/java/com/msg/network/request/auth/SignUpCompanyInstructorRequest.kt
  core/network/src/main/java/com/msg/network/request/auth/SignUpGovernmentRequest.kt
  core/network/src/main/java/com/msg/network/request/auth/SignUpJobClubTeacherRequest.kt
  core/network/src/main/java/com/msg/network/request/auth/SignUpProfessorRequest.kt
  core/network/src/main/java/com/msg/network/request/auth/SignUpStudentRequest.kt
  core/network/src/main/java/com/msg/network/request/certification/WriteCertificationRequest.kt
  core/network/src/main/java/com/msg/network/request/email/SendLinkToEmailRequest.kt
  core/network/src/main/java/com/msg/network/request/faq/AddFrequentlyAskedQuestionsRequest.kt
  core/network/src/main/java/com/msg/network/request/lecture/OpenLectureRequest.kt
  core/network/src/main/java/com/msg/network/request/post/WritePostRequest.kt
  core/network/src/main/java/com/msg/network/request/user/ChangePasswordRequest.kt
  core/network/src/main/java/com/msg/network/response/activity/GetDetailStudentActivityInfoResponse.kt
  core/network/src/main/java/com/msg/network/response/activity/GetStudentActivityListResponse.kt
  core/network/src/main/java/com/msg/network/response/admin/UseListContentResponse.kt
  core/network/src/main/java/com/msg/network/response/admin/UserListResponse.kt
  core/network/src/main/java/com/msg/network/response/auth/AuthTokenResponse.kt
  core/network/src/main/java/com/msg/network/response/certification/CertificationListResponse.kt
  core/network/src/main/java/com/msg/network/response/club/ClubDetailResponse.kt
  core/network/src/main/java/com/msg/network/response/club/ClubListResponse.kt
  core/network/src/main/java/com/msg/network/response/club/StudentBelongClubResponse.kt
  core/network/src/main/java/com/msg/network/response/email/GetEmailAuthenticateStatusResponse.kt
  core/network/src/main/java/com/msg/network/response/faq/GetFrequentlyAskedQuestionDetailResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/DetailLectureResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/DownloadExcelFileResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/GetLectureSignUpHistoryResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/GetTakingLectureStudentListResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/LectureListResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/SearchDepartmentResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/SearchDivisionResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/SearchLineResponse.kt
  core/network/src/main/java/com/msg/network/response/lecture/SearchProfessorResponse.kt
  core/network/src/main/java/com/msg/network/response/post/GetDetailPostResponse.kt
  core/network/src/main/java/com/msg/network/response/post/GetPostListResponse.kt
  core/network/src/main/java/com/msg/network/response/user/GetMyPageResponse.kt
  core/network/src/main/java/com/msg/network/util/AuthInterceptor.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High, ⚡️performance, ✨ Feature

#232 🔀 :: (#231) - Modify Unnecessary Code
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple
