Repository School-of-Company/Bitgoeul-Android, pull requests merged in 2024-08, with the labels that each got.

#247 🔀 :: (#246) App Icon Image Downgrade
  core/design-system/src/main/ic_launcher-playstore.png
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#249 🔀 :: (#248) Google Play Store 약관 준수를 위한 Icon Image 변경
  core/design-system/src/main/ic_launcher-playstore.png
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  core/design-system/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: 0️⃣ Priority: Critical

#253 🔀 :: (#252) - Refactor Unused CompositionLocalProvider Code
  core/design-system/src/main/res/values/strings.xml
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/my-page/src/main/java/com/example/my_page/PasswordChangeScreen.kt
  feature/post/src/main/java/com/msg/post/PostAddScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailSettingScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/AddActivityScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#255 🔀 :: (#254) - Use Destructuring Declaration
  feature/my-page/src/main/java/com/example/my_page/MyPageScreen.kt
  feature/my-page/src/main/java/com/example/my_page/PasswordChangeScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#257 🔀 :: (#256) - passwordchangescreen state manage viewmodel
  feature/my-page/src/main/java/com/example/my_page/PasswordChangeScreen.kt
  feature/my-page/src/main/java/com/example/my_page/viewmodel/MyPageViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#259 🔀 :: (#258) - certification module refactor
  core/design-system/src/main/res/values/strings.xml
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/CertificationScreen.kt
  feature/certification/src/main/java/com/msg/certification/viewmodel/CertificationViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#261 🔀 :: (#260) - club module use destructuring declaration
  feature/club/src/main/java/com/msg/club/ClubDetailScreen.kt
  feature/club/src/main/java/com/msg/club/ClubScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#263 🔀 :: (#262) - refactor email module
  core/design-system/src/main/java/com/msg/design_system/util/checkRegex.kt
  feature/email/src/main/java/com/bitgoeul/email/EmailSendInformScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputEmailScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputNewPasswordScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/PasswordChangeSuccessScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/viewmodel/EmailViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#266 🔀 :: (#265) - Use rememberSaveable
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/club/src/main/java/com/msg/club/ClubScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/EmailSendInformScreen.kt
  feature/my-page/src/main/java/com/example/my_page/MyPageScreen.kt
  feature/my-page/src/main/java/com/example/my_page/PasswordChangeScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#269 🔀 :: (#268) - refactor main module
  feature/main/src/main/java/com/msg/main/MainPageScreen.kt
  feature/main/src/main/java/com/msg/main/component/AddFaqItem.kt
  feature/main/src/main/java/com/msg/main/component/FaqItem.kt
  feature/main/src/main/java/com/msg/main/component/SchoolClubGridView.kt
  feature/main/src/main/java/com/msg/main/viewmodel/FaqViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#271 🔀 :: (#270) - refactor post module
  feature/post/src/main/java/com/msg/post/PostAddScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailSettingScreen.kt
  feature/post/src/main/java/com/msg/post/PostScreen.kt
  feature/post/src/main/java/com/msg/post/component/AddLinkSection.kt
  feature/post/src/main/java/com/msg/post/viewmodel/PostViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#273 🔀 :: (#272) - create modifier custom function
  core/design-system/src/main/java/com/msg/design_system/component/modifier/clickableSingle/MultipleEventsCutter.kt
  core/design-system/src/main/java/com/msg/design_system/component/modifier/clickableSingle/clickableSingle.kt
  core/design-system/src/main/java/com/msg/design_system/component/modifier/padding/padding.kt
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureList.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ✨ Feature

#275 🔀 :: (#274) - refactor signupscreen
  feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/msg/sign_up/util/enums/Keyboard.kt
  feature/sign-up/src/main/java/com/msg/sign_up/util/enums/SignUpState.kt
  feature/sign-up/src/main/java/com/msg/sign_up/util/keyboardAsState.kt
  feature/sign-up/src/main/java/com/msg/sign_up/viewmodel/SignUpViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#277 🔀 :: (#276) - refactor student activity module
  feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailSettingScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/AddActivityScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/StudentActivityScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/viewmodel/StudentActivityViewModel.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#279 🔀 :: (#278) - Fire Unused Code(core -> build.gradle.kts)
  core/data/build.gradle.kts
  core/datastore/build.gradle.kts
  core/design-system/build.gradle.kts
  core/domain/build.gradle.kts
  core/model/build.gradle.kts
  core/network/build.gradle.kts
  core/ui/build.gradle.kts
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#281 Refactoring main page
  app/build.gradle.kts
  app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
  app/src/main/java/com/msg/bitgoeul_android/navigation/TopLevelDestination.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulApp.kt
  app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulAppState.kt
  core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
  core/design-system/src/main/java/com/msg/design_system/component/navigation/BitgoeulNavigationBar.kt
  core/design-system/src/main/java/com/msg/design_system/theme/color/BitgoeulColor.kt
  core/design-system/src/main/java/com/msg/design_system/theme/color/ColorTheme.kt
  core/model/src/main/java/com/msg/model/enumdata/Field.kt
  core/model/src/main/java/com/msg/model/model/school/SchoolModel.kt
  core/network/src/main/java/com/msg/network/util/AuthInterceptor.kt
  feature/main/.gitignore
  feature/main/build.gradle.kts
  feature/main/proguard-rules.pro
  feature/main/src/androidTest/java/com/example/main/ExampleInstrumentedTest.kt
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/msg/main/ClubInfo.kt
  feature/main/src/main/java/com/msg/main/MainPageScreen.kt
  feature/main/src/main/java/com/msg/main/banner/club/AiFusionAndIntegrationClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/club/CultureIndustryClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/club/EnergyIndustryClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/club/FutureTransportClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/club/MedicalHealthClubBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/AiFusionAndIntegrationBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/CultureIndustryBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/EnergyIndustryBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/FutureTransportationBanner.kt
  feature/main/src/main/java/com/msg/main/banner/industry/MedicalHealthBanner.kt
  feature/main/src/main/java/com/msg/main/component/AddFaqItem.kt
  feature/main/src/main/java/com/msg/main/component/BitgoeulInfoCardView.kt
  feature/main/src/main/java/com/msg/main/component/ClubChipView.kt
  feature/main/src/main/java/com/msg/main/component/ClubInfoCardView.kt
  feature/main/src/main/java/com/msg/main/component/CollegeCardView.kt
  feature/main/src/main/java/com/msg/main/component/FaqItem.kt
  feature/main/src/main/java/com/msg/main/component/FaqSection.kt
  feature/main/src/main/java/com/msg/main/component/GovernmentBannerItem.kt
  feature/main/src/main/java/com/msg/main/component/HighSchoolCardView.kt
  feature/main/src/main/java/com/msg/main/component/HorizontalInfiniteLoopPager.kt
  feature/main/src/main/java/com/msg/main/component/SchoolClubGridView.kt
  feature/main/src/main/java/com/msg/main/navigation/MainPageNavigation.kt
  feature/main/src/main/java/com/msg/main/viewmodel/FaqViewModel.kt
  feature/main/src/test/java/com/example/main/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High

#284 🔀 :: (#283) Delete Feature Patch Lecture
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepository.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/usecase/lecture/PatchLecture.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSourceImpl.kt
Labels: 0️⃣ Priority: Critical
