Repository School-of-Company/Bitgoeul-Android, pull requests merged in 2024-07, with the labels that each got.

#235 🔀 :: (#234) - Apply changed or added api
  core/data/build.gradle.kts
  core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
  core/data/src/main/java/com/msg/data/mapper/club/PatchClubMapper.kt
  core/data/src/main/java/com/msg/data/mapper/lecture/DetailLectureMapper.kt
  core/data/src/main/java/com/msg/data/mapper/lecture/OpenLectureMapper.kt
  core/data/src/main/java/com/msg/data/mapper/map/GetLocationMapper.kt
  core/data/src/main/java/com/msg/data/mapper/school/GetSchoolListMapper.kt
  core/data/src/main/java/com/msg/data/mapper/school/PostSchoolMapper.kt
  core/data/src/main/java/com/msg/data/repository/club/ClubRepository.kt
  core/data/src/main/java/com/msg/data/repository/club/ClubRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepository.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/map/MapRepository.kt
  core/data/src/main/java/com/msg/data/repository/map/MapRepositoryImpl.kt
  core/data/src/main/java/com/msg/data/repository/school/SchoolRepository.kt
  core/data/src/main/java/com/msg/data/repository/school/SchoolRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/usecase/club/DeleteClubUseCase.kt
  core/domain/src/main/java/com/msg/domain/usecase/club/PatchClubUseCase.kt
  core/domain/src/main/java/com/msg/domain/usecase/lecture/PatchLecture.kt
  core/domain/src/main/java/com/msg/domain/usecase/map/GetLocationUseCase.kt
  core/domain/src/main/java/com/msg/domain/usecase/school/GetSchoolListUseCase.kt
  core/domain/src/main/java/com/msg/domain/usecase/school/GetSchoolNameUseCase.kt
  core/domain/src/main/java/com/msg/domain/usecase/school/PostSchoolUseCase.kt
  core/model/build.gradle.kts
  core/model/src/main/java/com/msg/model/entity/lecture/DetailLectureEntity.kt
  core/model/src/main/java/com/msg/model/entity/map/GetLocationEntity.kt
  core/model/src/main/java/com/msg/model/entity/school/GetSchoolListEntity.kt
  core/model/src/main/java/com/msg/model/model/school/SchoolModel.kt
  core/model/src/main/java/com/msg/model/param/club/PatchClubParam.kt
  core/model/src/main/java/com/msg/model/param/lecture/OpenLectureParam.kt
  core/model/src/main/java/com/msg/model/param/school/PostSchoolParam.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/msg/network/api/ClubAPI.kt
  core/network/src/main/java/com/msg/network/api/LectureAPI.kt
  core/network/src/main/java/com/msg/network/api/MapAPI.kt
  core/network/src/main/java/com/msg/network/api/SchoolAPI.kt
  core/network/src/main/java/com/msg/network/datasource/club/ClubDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/club/ClubDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/lecture/LectureDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/map/MapDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/map/MapDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/datasource/school/SchoolDataSource.kt
  core/network/src/main/java/com/msg/network/datasource/school/SchoolDataSourceImpl.kt
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
  core/network/src/main/java/com/msg/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/msg/network/request/club/PatchClubRequest.kt
  core/network/src/main/java/com/msg/network/request/lecture/OpenLectureRequest.kt
  core/network/src/main/java/com/msg/network/request/school/PostSchoolRequest.kt
  core/network/src/main/java/com/msg/network/response/lecture/DetailLectureResponse.kt
  core/network/src/main/java/com/msg/network/response/map/GetLocationResponse.kt
  core/network/src/main/java/com/msg/network/response/school/GetSchoolListResponse.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/viewmodel/LectureViewModel.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High

#239 🔀 :: (#238) Fix Lecture Response Converter Error
  core/data/src/main/java/com/msg/data/mapper/lecture/LectureListMapper.kt
  core/data/src/main/java/com/msg/data/repository/lecture/LectureRepositoryImpl.kt
  core/domain/src/main/java/com/msg/domain/usecase/lecture/GetLectureListUseCase.kt
  core/model/src/main/java/com/msg/model/entity/lecture/LectureListEntity.kt
  core/model/src/main/java/com/msg/model/enumdata/LectureStatus.kt
  core/network/src/main/java/com/msg/network/di/NetworkModule.kt
  core/network/src/main/java/com/msg/network/response/lecture/LectureListResponse.kt
  core/network/src/main/java/com/msg/network/util/UUIDAdapter.kt
  core/network/src/main/java/com/msg/network/util/makeRequest.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureListScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureCard.kt
  feature/lecture/src/main/java/com/msg/lecture/component/LectureList.kt
  feature/lecture/src/main/java/com/msg/lecture/viewmodel/LectureViewModel.kt
Labels: 0️⃣ Priority: Critical

#242 🔀 :: (#241) - 화면 클릭시 키보드가 내려갈 수 있게 수정하였습니다
  feature/certification/src/main/java/com/msg/certification/AddCertificationScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/EmailSendInformScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputEmailScreen.kt
  feature/email/src/main/java/com/bitgoeul/email/InputNewPasswordScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureDetailSettingScreen.kt
  feature/lecture/src/main/java/com/msg/lecture/LectureOpenScreen.kt
  feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
  feature/my-page/src/main/java/com/example/my_page/PasswordChangeScreen.kt
  feature/post/src/main/java/com/msg/post/PostAddScreen.kt
  feature/post/src/main/java/com/msg/post/PostDetailSettingScreen.kt
  feature/student-activity/src/main/java/com/msg/student_activity/AddActivityScreen.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️ Simple
